In [72]:
# coding=utf-8

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from datetime import datetime

%matplotlib inline

In [73]:
rnn_unit = 10  # 隐藏层单元数量
input_size = 4
output_size = 1
lr = 0.0005  # 学习率
location  = "C:/Users/workspace/brad_public_workspace_on_win/SH_tongliang/data/数据库/火币日线/"
file = "11_14_huobi_btcusdt_copy_for_ML.csv"
# ——————————————————导入数据——————————————————————
df = pd.read_csv(location+file, engine="python")  # 读入IF期货数据
df.loc[1:, 'label'] = label  # 标签，以收盘价差作为涨跌,含幅度变化
data = df.iloc[:, [1, 2, 3, 4, 5]].values  # numpy.ndarray, 几个特征量：开盘价、最高价、最低价、收盘价
label = []
for i in range(1, len(data)):
    label.append(round(data[i, 3] - data[i - 1, 3], 4))

date = datetime.now().strftime('%Y-%m-%d')

In [75]:
# 函数一：获取训练集
def get_train_data(batch_size=80,
                   time_step=20,
                   train_begin=0,
                   train_end=120000):
    pass

batch_size=80
time_step=20
train_begin=0
train_end=1200

In [76]:
batch_index = []
data_train = data[train_begin:train_end]

In [77]:
normalized_train_data = (
    data_train - np.mean(data_train, axis=0)) / np.std(
        data_train, axis=0)  # 标准化
# print('type(normalized_train_data): ', type(normalized_train_data))
# print('normalized_train_data.shape: ', normalized_train_data.shape)
# normalized_train_data.shape: (5800, 8)
train_x, train_y = [], []  # 训练集
print (normalized_train_data)

[[-1.03317008 -0.96123828 -1.13259015 -0.97458042         nan]
 [-0.97319774 -0.97516928 -1.02307114 -1.02468269         nan]
 [-1.0216766  -1.02780351 -1.03617625 -1.05409779         nan]
 ...
 [-0.76160875 -0.79996705 -0.7438997  -0.78993281         nan]
 [-0.78868407 -0.7948252  -0.74069037 -0.76421381         nan]
 [-0.76270215 -0.80003086 -0.72947596 -0.76084707         nan]]


In [78]:
normalized_train_data

array([[-1.03317008, -0.96123828, -1.13259015, -0.97458042,         nan],
       [-0.97319774, -0.97516928, -1.02307114, -1.02468269,         nan],
       [-1.0216766 , -1.02780351, -1.03617625, -1.05409779,         nan],
       ...,
       [-0.76160875, -0.79996705, -0.7438997 , -0.78993281,         nan],
       [-0.78868407, -0.7948252 , -0.74069037, -0.76421381,         nan],
       [-0.76270215, -0.80003086, -0.72947596, -0.76084707,         nan]])

In [79]:
normalized_train_data[0:20, 3, np.newaxis]

array([[-0.97458042],
       [-1.02468269],
       [-1.05409779],
       [-0.9522428 ],
       [-0.90102804],
       [-0.80487456],
       [-0.72323834],
       [-0.55364959],
       [-0.44700797],
       [-0.4515421 ],
       [-0.37404477],
       [-0.47896642],
       [-0.5602184 ],
       [-0.39059305],
       [-0.51124325],
       [-0.63139942],
       [-0.88493354],
       [-0.8770839 ],
       [-0.69324504],
       [-0.76232551]])

In [80]:
normalized_train_data[0:20, 4, np.newaxis]

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]])

In [54]:
normalized_train_data[i:i + time_step, :3]

array([[-1.03317008, -0.96123828, -1.13259015],
       [-0.97319774, -0.97516928, -1.02307114],
       [-1.0216766 , -1.02780351, -1.03617625],
       [-1.05348022, -0.96550355, -1.03195665],
       [-0.94951232, -0.88540362, -0.93986785],
       [-0.8997426 , -0.82860823, -0.8683131 ],
       [-0.80381977, -0.75948719, -0.77351808],
       [-0.72248412, -0.58844612, -0.66186898],
       [-0.55260516, -0.51358543, -0.54427592],
       [-0.44628956, -0.51507324, -0.49664308],
       [-0.45057173, -0.4399808 , -0.35960333],
       [-0.37462262, -0.44138129, -0.42255658],
       [-0.47797617, -0.53975476, -0.49574642],
       [-0.55914726, -0.45860362, -0.49598986],
       [-0.39081881, -0.39186711, -0.45795256],
       [-0.51022592, -0.52541738, -0.60249023],
       [-0.63029859, -0.64191996, -0.87266254],
       [-0.8839706 , -0.78995539, -1.21170772],
       [-0.87662034, -0.71260606, -1.03156715],
       [-0.6920445 , -0.73916498, -0.79599558]])

In [70]:
normalized_train_data[i:i + time_step, 4, np.newaxis]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [69]:
for i in range(len(normalized_train_data) - time_step):
    if i % batch_size == 0:
        batch_index.append(i)
    # x.shape: (20, 7)
    x = normalized_train_data[i:i + time_step, :3]
    # y.shape: (20, 1)
    y = normalized_train_data[i:i + time_step, 3, np.newaxis] 
    train_x.append(x.tolist())
    train_y.append(y.tolist())

In [3]:

# print('train_data x.shape: ', x.shape)
# train_data x.shape:  (20, 6)
# print('train_data y.shape: ', y.shape)
# train_data y.shape:  (20, 1)
# print('train_data y: ', y)
batch_index.append((len(normalized_train_data) - time_step))
#     return batch_index, train_x, train_y

[[-1.03317008 -0.96123828 -1.13259015 -0.97458042]
 [-0.97319774 -0.97516928 -1.02307114 -1.02468269]
 [-1.0216766  -1.02780351 -1.03617625 -1.05409779]
 ...
 [-0.76160875 -0.79996705 -0.7438997  -0.78993281]
 [-0.78868407 -0.7948252  -0.74069037 -0.76421381]
 [-0.76270215 -0.80003086 -0.72947596 -0.76084707]]


IndexError: index 4 is out of bounds for axis 1 with size 4

In [68]:
# 获取训练集
def get_train_data(batch_size=80,
                   time_step=20,
                   train_begin=0,
                   train_end=120000):
    batch_index = []
    data_train = data[train_begin:train_end]
    normalized_train_data = (
        data_train - np.mean(data_train, axis=0)) / np.std(
            data_train, axis=0)  # 标准化
    # print('type(normalized_train_data): ', type(normalized_train_data))
    # print('normalized_train_data.shape: ', normalized_train_data.shape)
    # normalized_train_data.shape: (5800, 8)
    train_x, train_y = [], []  # 训练集
    print (normalized_train_data)
    for i in range(len(normalized_train_data) - time_step):
        if i % batch_size == 0:
            batch_index.append(i)
        # x.shape: (20, 7)
        x = normalized_train_data[i:i + time_step, :3]
        # y.shape: (20, 1)
        y = normalized_train_data[i:i + time_step, 4, np.newaxis] 
        train_x.append(x.tolist())
        train_y.append(y.tolist())
    # print('train_data x.shape: ', x.shape)
    # train_data x.shape:  (20, 6)
    # print('train_data y.shape: ', y.shape)
    # train_data y.shape:  (20, 1)
    # print('train_data y: ', y)
    batch_index.append((len(normalized_train_data) - time_step))
    return batch_index, train_x, train_y


# 获取测试集
def get_test_data(time_step=20, test_begin=120000):
    data_test = data[test_begin:]
    # print('data_test: ', data_test)
    test_y = data_test[:, 4]
    # print('test_y4: ', test_y)
    # data_train = data[:test_begin]
    mean = np.mean(data_test, axis=0)  # 改用已知的训练数据，避免用到未来数据
    std = np.std(data_test, axis=0)  # 同上
    normalized_test_data = (data_test - mean) / std  # 标准化
    size = (
        len(normalized_test_data) + time_step - 1) // time_step  # 有size个sample
    test_x, test_y = [], []
    for i in range(size - 1):
        x = normalized_test_data[i * time_step:(i + 1) * time_step, :3]
        y = normalized_test_data[i * time_step:(i + 1) * time_step, 4]
        test_x.append(x.tolist())
        test_y.extend(y)
    # print('type(x): ', type(x))
    # print('test_data x.shape: ', x.shape)
    # print('test_data y.shape: ', y.shape)
    # print('test_y3: ', test_y)
    test_x.append((normalized_test_data[(i + 1) * time_step:, :3]).tolist())
    test_y.extend((normalized_test_data[(i + 1) * time_step:, 4]).tolist())
    return mean, std, test_x, test_y


# ——————————————————定义神经网络变量——————————————————
# 输入层、输出层的权重、偏置

weights = {
    'in': tf.Variable(tf.random_normal([input_size, rnn_unit])),
    'out': tf.Variable(tf.random_normal([rnn_unit, 1]))
}
biases = {
    'in': tf.Variable(tf.constant(0.1, shape=[
        rnn_unit,
    ])),
    'out': tf.Variable(tf.constant(0.1, shape=[
        1,
    ]))
}


# ——————————————————定义神经网络变量——————————————————
def lstm(X):

    batch_size = tf.shape(X)[0]
    time_step = tf.shape(X)[1]
    w_in = weights['in']
    b_in = biases['in']
    input = tf.reshape(X, [-1, input_size])  # 需要将tensor转成2维进行计算，计算后的结果作为隐藏层的输入
    input_rnn = tf.matmul(input, w_in) + b_in
    input_rnn = tf.reshape(
        input_rnn, [-1, time_step, rnn_unit])  # 将tensor转成3维，作为lstm cell的输入
    cell = tf.nn.rnn_cell.BasicLSTMCell(rnn_unit)
    init_state = cell.zero_state(batch_size, dtype=tf.float32)
    output_rnn, final_states = tf.nn.dynamic_rnn(
        cell, input_rnn, initial_state=init_state, dtype=tf.float32)
    output = tf.reshape(output_rnn, [-1, rnn_unit])
    w_out = weights['out']
    b_out = biases['out']
    pred = tf.matmul(output, w_out) + b_out
    return pred, final_states


# ————————————————训练模型————————————————————


def train_lstm(batch_size=80, time_step=20, train_begin=0, train_end=120000):
    X = tf.placeholder(tf.float32, shape=[None, time_step, input_size])
    Y = tf.placeholder(tf.float32, shape=[None, time_step, output_size])
    batch_index, train_x, train_y = get_train_data(batch_size, time_step,
                                                   train_begin, train_end)
    with tf.variable_scope("sec_lstm"):
        pred, _ = lstm(X)
    loss = tf.reduce_mean(
        tf.square(tf.reshape(pred, [-1]) - tf.reshape(Y, [-1])))
    train_op = tf.train.AdamOptimizer(lr).minimize(loss)
    saver = tf.train.Saver(tf.global_variables(), max_to_keep=15)

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        for i in range(200):  # 这个迭代次数，可以更改，越大预测效果会更好，但需要更长时间
            for step in range(len(batch_index) - 1):
                _, loss_ = sess.run(
                    [train_op, loss],
                    feed_dict={
                        X: train_x[batch_index[step]:batch_index[step + 1]],
                        Y: train_y[batch_index[step]:batch_index[step + 1]]
                    })
            print("Number of iterations:", i, " loss:", loss_)
            with open( location+ 'loss_' + date + '.csv', 'w') as f:
                f.write(str(loss_) + '\n')
        # print("model_save: ", saver.save(sess, 'model_save2\\modle.ckpt'))
        print("model_save: ", saver.save(sess, location+'model_save5/modle.ckpt'))
        # 我是在window下跑的，这个地址是存放模型的地方，模型参数文件名为modle.ckpt
        # 在Linux下面用 'model_save2/modle.ckpt'
        print("The train has finished")


train_lstm()


# ————————————————预测模型————————————————————
def prediction(time_step=20):
    X = tf.placeholder(tf.float32, shape=[None, time_step, input_size])
    mean, std, test_x, test_y = get_test_data(time_step)
    with tf.variable_scope("sec_lstm", reuse=True):
        pred, _ = lstm(X)
    saver = tf.train.Saver(tf.global_variables())
    with tf.Session() as sess:
        # 参数恢复
        module_file = tf.train.latest_checkpoint('model_save5')
        saver.restore(sess, module_file)
        test_predict = []
        for step in range(len(test_x) - 1):
            # prob.shape: (20, 1)
            prob = sess.run(pred, feed_dict={X: [test_x[step]]})
            # print('prob.shape: ', prob.shape)
            # predict.shape: (20, )
            predict = prob.reshape((-1))
            test_predict.extend(predict)
        # print('test_y1: ', test_y)
        test_y = np.array(test_y) * std[4] + mean[4]
        # print('test_y2: ', test_y)
        # print('test_y.shape: ', test_y.shape)
        test_predict = np.array(test_predict) * std[4] + mean[4]
        acc = np.average(
            np.abs(test_predict - test_y[:len(test_predict)]) /
            test_y[:len(test_predict)])  # 偏差程度
        print("The accuracy of this predicet:", 1 - acc)
        with open(location+'test_y_' + date + '.csv', 'w') as f:
            f.write(str(test_y) + '\n')

        with open(location+'test_predict_' + date + '.csv', 'w') as f:
            f.write(str(test_predict))

        with open(location+'accuracy_' + date + '.csv', 'w') as f:
            f.write(str(1-acc) + '\n')
        # 以折线图表示结果
        # print('len(test_predict): ', len(test_predict))
        # print('len(test_y): ', len(test_y))
        # print('len(data): ', len(data))
        plt.figure()
        # fig = plt.subplot(111)
        plt.plot(
            list(range(len(test_predict))),
            test_predict,
            color='blue',
            label='predict',
        )
        plt.plot(list(range(len(test_y))), test_y, color='red', label='real')
        # plt.plot(
        #     list(range(len(data))), data, color='r', label='real_all')
        plt.legend(loc='upper left')
        plt.ylabel('high')
        plt.show()


prediction()
# The accuracy of this predict: 0.016965209201494337

[[-1.03317008 -0.96123828 -1.13259015 -0.97458042         nan]
 [-0.97319774 -0.97516928 -1.02307114 -1.02468269         nan]
 [-1.0216766  -1.02780351 -1.03617625 -1.05409779         nan]
 ...
 [-0.76160875 -0.79996705 -0.7438997  -0.78993281         nan]
 [-0.78868407 -0.7948252  -0.74069037 -0.76421381         nan]
 [-0.76270215 -0.80003086 -0.72947596 -0.76084707         nan]]


ValueError: Cannot feed value of shape (80, 20, 3) for Tensor 'Placeholder_2:0', which has shape '(?, 20, 4)'